### ISSUE TITLE
ecospat.boyce generates warning: using | instead of || in comparison

### ISSUE THREAD

**Issue by plantarum** [ecospat/ecospat#16]
`ecospat.boyce` contains the line:

https://github.com/ecospat/ecospat/blob/fa5b4dfc7c25ab154e46a850a3f34224f29c9549/ecospat/R/ecospat.boyce.R#L36

This line only runs when `fit` is a RasterLayer, so it doesn't get called in the example from the help file.

When `fit` is a RasterLayer, this line will generate a warning:

```
boyce81<-ecospat.boyce (pr81, coordinates(iNatcsv))
Warning message:
In if (class(obs) == "data.frame" | class(obs) == "matrix") { :
  the condition has length > 1 and only the first element will be used 
```

In most cases this will be fine, but it suggests there is a problem and may worry or confuse users (as it did me!). It's generally good practice to investigate all warnings to make sure they don't indicate a substantive problem with our analysis.

The problem is due to the use of a single `|` in the comparison. The doubled form `||` is correct here, following the documentation for Logical Operators:

     & and && indicate logical AND and | and || indicate
     logical OR.  The shorter form performs elementwise comparisons in
     much the same way as arithmetic operators.  The longer form
     evaluates left to right examining only the first element of each
     vector.  Evaluation proceeds only until the result is determined.
     **The longer form is appropriate for programming control-flow and
     typically preferred in if clauses.**

Consequently, replacing the `|` with a `||` will eliminate the warning.

**Comment by ecospat** [comment]
thank you, we now use ||
