### ISSUE TITLE
documentation missing for ecospat.plot.niche.dyn

### ISSUE THREAD

**Issue by plantarum** [ecospat/ecospat#17]
The existing documentation doesn't explain what the colours mean in the plots generated by ecospat.plot.niche.dyn. i.e., there is no indication of which color is expansion and which is unfilling. I did send you a pull request #11 that provided this documentation, but you rejected it.

It would be really convenient to have a quick way to remind myself which color is which when I use this function. Since you didn't like the documentation I offered, is there something I could do to make it acceptable, or are you planning to provide this documentation yourself?

**Comment by ecospat** [comment]
sorry I didn't have time to take into account your inputs before. I fixed some issues in the code of the function and added documentation based on your suggestions.

**Comment by plantarum** [comment]
Thanks!

For your information, I have written a short tutorial for ecospat.grid.clim.dyn, including using some related tools to collect observation and distribution data. It overlaps a bit with the vignette, but includes some other steps we use  in our lab.

https://plantarum.ca/2021/07/29/ecospat/

Best,

Tyler
