### ISSUE TITLE
can't use geomask with ecospat.grid.clim.dyn

### ISSUE THREAD

**Issue by plantarum** [ecospat/ecospat#18]
Hi,

I'm using ecospat.grid.clim.dyn to compare ecological range overlap between two species. The help file indicates that I should be able to use a SpatialPolygon or raster object to limit the background extent when doing analyses in geographic space.

However, when I try to do this, using a shapefile, I get the error:

```
+ Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘proj4string<-’ for signature ‘"SpatialPolygonsDataFrame", "logical"’
 ```

In investigating this, I found the error is generated by the code:

https://github.com/ecospat/ecospat/blob/fa5b4dfc7c25ab154e46a850a3f34224f29c9549/ecospat/R/ecospat.nichedynamic.R#L136-L138

Specifically, the line `proj4string(geomask) <- NA` 

The problem is resolved by removing this line, or replacing it with `crs(geomask) <- NA`. I don't understand why `proj4string` is used here, and don't know if either of these 'fixes' is correct.

Here's an example that demonstrates the error. It masks the analysis to a single Canton in Switzerland. In my actual analysis, I want to mask an analysis to the boundaries of a continent, excluding the surrounding ocean from the estimated range.

```R
library(ecospat)
library(raster)
library(rgdal)

data(ecospat.testData)
coordinates(ecospat.testData) <- ~long+lat

epsg <- make_EPSG()
swissGrid <- epsg[grep("^21781$", epsg$code, ignore.case = TRUE), "prj4"]
crs(ecospat.testData) <- swissGrid

swissMap1 <- getData(name = "GADM", country = "CHE", level = 1)
vaudMap <- subset(swissMap1, NAME_1 == "Vaud")

ecospat.testDataLL <- spTransform(ecospat.testData, crs(swissMap1))

atrata <- subset(ecospat.testDataLL, ecospat.testData$Achillea_atrata == 1)
mill <- subset(ecospat.testDataLL,
              ecospat.testData$Achillea_millefolium == 1) 

vaudBG <- spsample(vaudMap, n = 1000, type = "random")


## This works:
grid.mill <- ecospat.grid.clim.dyn(glob = coordinates(vaudBG),
                                  glob1 = coordinates(vaudBG),
                                  sp = coordinates(mill), R = 100)

grid.atrata <- ecospat.grid.clim.dyn(glob = coordinates(vaudBG),
                                  glob1 = coordinates(vaudBG),
                                  sp = coordinates(atrata), R = 100)

ecospat.plot.niche.dyn(grid.mill, grid.atrata, quant = 0.05,
                       interest = 2, title = "Range Overlap",
                       name.axis1 = "LON", name.axis2 = "LAT")

## This fails with the error:
##  Error in (function (classes, fdef, mtable)  : 
##    unable to find an inherited method for function ‘proj4string<-’ for
##    signature ‘"SpatialPolygonsDataFrame", "logical"’

grid.millM <- ecospat.grid.clim.dyn(glob = coordinates(vaudBG),
                                  glob1 = coordinates(vaudBG),
                                  sp = coordinates(mill), R = 100,
                                  geomask = vaudMap)

grid.atrataM <- ecospat.grid.clim.dyn(glob = coordinates(vaudBG),
                                  glob1 = coordinates(vaudBG),
                                  sp = coordinates(atrata), R = 100,
                                  geomask = vaudMap)

ecospat.plot.niche.dyn(grid.millM, grid.atrataM, quant = 0.05,
                       interest = 1, title = "Range Overlap",
                       name.axis1 = "LON", name.axis2 = "LAT")
```

Can you tell me if I'm doing something wrong, of if this is a problem with the code?

Best,

Tyler

**Comment by plantarum** [comment]
This is the analysis I'm trying to get:

![masked-analysis](https://user-images.githubusercontent.com/5727138/96296336-23df3b80-0fbd-11eb-93cb-72cc4d8883a8.jpg)

This is the analysis without the geographic mask:

![unmasked](https://user-images.githubusercontent.com/5727138/96296441-48d3ae80-0fbd-11eb-81af-9eb50149cfae.jpg)

**Comment by ecospat** [comment]
thanks for point to this error and sorry for the delayed response.  We changed proj4string to crs.
