### ISSUE TITLE
Missing line ecospat.boyce.R

### ISSUE THREAD

**Issue by bfakos** [ecospat/ecospat#20]
Hello,
I think a line something like this
interval <- cbind(vec.mov, c(vec.mov[-1], maxi))
is missing after L57.
L59 throws an error if length(nclass) == 1 and nclass != 1, since interval is a numeric vector instead of a data.frame (that is required by apply()).
Have a nice day,
Ákos Bede-Fazekas

**Comment by ecospat** [comment]
thanks you, we fixed the code
