### ISSUE TITLE
Function boycei() is overcomplicated 

### ISSUE THREAD

**Issue by bfakos** [ecospat/ecospat#21]
Hello,
Although it is not an issue, it may greatly reduce the performance of ecospat.boyce(). The source code of the internal function boycei() is overcomplicated:
- making a copy of fit and obs is unnecessary (L10-11), 
- fit is the same as fit[] (L12, L14)
- L13 and L15 are unnecessary
- L19 is unnecessary
I recommend the following:

boycei <- function(interval, obs, fit) {
  pi <- sum(as.numeric(obs >= interval[1] & obs <= interval[2])) / length(obs)
  ei <- sum(as.numeric(fit >= interval[1] & fit <= interval[2])) / length(fit)
  return(pi/ei)
}

Have a nice week,
Ákos Bede-Fazekas

**Comment by ecospat** [comment]
thank you for the simplification of the code, now implemented
