### ISSUE TITLE
Is there a way to include categorical variables when calculating niche overlap/equivalence with ecospat.grid.clim.dyn

### ISSUE THREAD

**Issue by AndreMBellve** [ecospat/ecospat#26]
I am currently working on some species distribution models, but some of the predictive layers I am using include are categorical.

I know that Dudi's PCA is not designed to handle these, but I was wondering if there is a prescribed way of including categorical variables in the niche space analyses. 

Can `ecospat.grid.clim.dyn()` handle other types of dimensional compression techniques (e.g. mixed PCA), and, if so, is there a recommended way to deal with this that I have missed? 

Or is it just better to use `dismo`'s inbuilt niche metric functions for this (e.g. `nicheOverlap` / `nicheEquivalence`)?

**Comment by bpetitpi** [comment]
Hello, 

Sorry for the late reply. `ecospat.grid.clim.dyn` shoud work with any one or two colums coordinates. So if you produce a PCA based on any library or tool and you retrieve the scores, you should be able to apply the _gridding_ to your scores. Note that I haven't yet looked into the similar tools in dismo, and they might work as well. 

I hope it helps. 
Blaise
