### ISSUE TITLE
Ecospate niche similarity tests results interpretation 

### ISSUE THREAD

**Issue by SDMENM** [ecospat/ecospat#27]
Hey Niche Modelers,

If I run niche conservatism test " alternative=greater" , I get a higher P value (>0.05), which I assume would be the case where I can say there is no significant niche conservatism. However,
When I run niche divergence test " alternative=lower", then again I get a higher P value  (>0.05), which suggests that there is no significant niche divergence. 
Could it be the case to have no significant conservatism and no significant divergence? or I am missing something?  

I would like to hear your thoughts about interpretation of such kind of results.

**Comment by bpetitpi** [comment]
Dear Jan, 
Sorry for the late response. Here is my appreciation about your results : 
If the test is not significant on both alternative, it means that your observed overlap is just as random as you expect by comparing two different species. It is neither lower than two random niches, nor higher. So depending your case study and what you want to test, it would just lead to the conclusion that there is no more conservatism than between two random niches. 
I hope it helped, 
Blaise
