### ISSUE TITLE
Why I receive such a error warning and what should I check my data?

### ISSUE THREAD

**Issue by yutingzhouBJFU** [ecospat/ecospat#33]
Recently, I used ecospat package to compare the a pest's niche shift, but I failed to receive the right results I wonder, instead it give the wrong warning as following：
> for(i in 1:4) {z[[i]] <- ecospat.grid.clim.dyn(total.scores.back,
+                                   scores.back[[i]],
+                                   scores.spec[[i]],
+                                   th.env = 0.25,
+                                   R = R)}
Error in quantile.default(raster::extract(x.dens, x), th) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

Could someone kindly help me tell the reason for the warning?

**Comment by FlavienCollart** [comment]
Hello,
Sorry for the late answer. It seems that you have NA's in at least one of your object.

**Comment by yutingzhouBJFU** [comment]
您的来信已经收到，我将尽快阅读回复，祝好！
