### ISSUE TITLE
Allow users to set plot parameters in ecospat

### ISSUE THREAD

**Issue by plantarum** [ecospat/ecospat#37]
I'm preparing some figures for publication, using the `ecospat.plot.niche.dyn` function. In preparing my panels, I need to adjust the margins and other decorations on the plot. This is not possible with the current version of the code:

https://github.com/ecospat/ecospat/blob/be63ddcc23500fb6f52e2faac9e8648252e65c4f/ecospat/R/ecospat.nichedynamic.R#L242-L244

However, much of what I want to do is easily added, via the `...` argument. If you add this to the function defintion:

```{r}
ecospat.plot.niche.dyn <- function (z1, z2, quant = 0, title = "", name.axis1 = "Axis 1", 
                        name.axis2 = "Axis 2", interest = 1,
                        col.unf = "green", col.exp = "red", 
                        col.stab = "blue", colZ1 = "green3",
                        colZ2 = "red3", transparency = 70, ...) 
```

And add the `...` argument to the plot commands further down, i.e., 

```{r}
        plot(x, y1, type = "n", xlab = name.axis1, ylab =
            "density of occurrence", ...)
```

and

```{r}
        if (interest == 1) {
            plot(z1$z.uncor, col = gray(100:0/100), legend = F, 
                 xlab = name.axis1, ylab = name.axis2, ...)
        }
        if (interest == 2) {
            plot(z2$z.uncor, col = gray(100:0/100), legend = F, 
                 xlab = name.axis1, ylab = name.axis2, ...)
        }

```

Then we could easily pass options, e.g.:

```{r}
ecospat.plot.niche.dyn(grid.clim.nat, grid.clim.inv,
           name.axis1 = "PC1",
           name.axis2 = "PC2", cex.axis = 0.75
           )
```

It's only a few characters, but it provides a lot more flexibility to format plots.

Thanks,

Tyler

**Comment by FlavienCollart** [comment]
Hello,
Thank you for your help and sorry for the late answer. Your proposed changes were added in the dev branch for now.
