### ISSUE TITLE
maptools, rgdal and rgeos retiring soon

### ISSUE THREAD

**Issue by rsbivand** [ecospat/ecospat#41]
Please note that **maptools**, **rgdal** and **rgeos** are retiring, https://r-spatial.org/r/2022/04/12/evolution.html. **ecospat** uses `maptools::spRbind()`. **raster** no longer uses **rgdal** or **rgeos**, using **terra** instead. Also please fix #40 ASAP, as it breaks reverse dependency checking.

**Comment by rsbivand** [comment]
New blog:

This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.


Best to be completed June 2023.

**Comment by rsbivand** [comment]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

You appear to use `maptools::spRbind` in ecospat.makeDataFrame.R (but do not declare it in NAMESPACE). `sp::rbind` is a feasible replacement, and remove maptools from Imports. Then run CMD check under a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path (see https://r-spatial.org/r/2023/04/10/evolution3.html). Then you may find other uses of retiring packages which also need fixing, best by June, latest October 2023.

**Comment by rsbivand** [comment]
Please do take action immediately. Refer to https://cran.r-project.org/web/checks/check_results_ecospat.html, which is the same as I have been seeing, recently as: 
[00check.log](https://github.com/ecospat/ecospat/files/11626974/00check.log).

**Comment by rsbivand** [comment]
Very likely related to:
```
biomod2 4.2-3 loaded.
 /!\ Since version 4.2 biomod2 relies on terra and may thus return SpatRaster that can easily be converted in RasterStack with `stack()`. We apologize for the trouble @('_')@
```

**Comment by rsbivand** [comment]
Unfortunately, @ecospat @vdicolab @fbreiner etc., `3.5.1` does not address this issue. Only three months remain to retain this package on CRAN when `maptools` etc. retire in October 2023. Please act now, you were first warned a long time ago.

**Comment by FlavienCollart** [comment]
We are currently working on it! We try to do our best to finish the transitions before October.
Sorry for the late answer and thank you for helping us.
Best,
Flavien

**Comment by rsbivand** [comment]
@FlavienCollart Less than three weeks remain to fix this.

**Comment by FlavienCollart** [comment]
We have finished the transitions. We are still working on a function issue and we will submit then asap our new version to cran.

**Comment by rsbivand** [comment]
@FlavienCollart R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos. It remains the case that many packages importing the raster package needlessly depend on retiring packages, as raster stopped using them a year ago.
