### ISSUE TITLE
ecospat.ESM.EnsembleModeling - Error 

### ISSUE THREAD

**Issue by rbfontana** [ecospat/ecospat#53]
Hello, 
I've been trying to use the ESMs (Ensemble of Small Models) to SDM for a list of species (19). However, for some species (4) the function "ecospat.ESM.EnsembleModeling" gets an error.
In the previous function "ecospat.ESM.Modeling" I've got some warnings for these species. 
Follows the code, warnings, and error messages.

ESM.I.hoehnei<- ecospat.ESM.Modeling(data=biomod.data.I.hoehnei,                                     models=c("GLM","MAXENT.Phillips.2","RF"),
                                     NbRunEval=5,
                                     DataSplit=80,
                                     Prevalence=0.5,
                                     weighting.score=c("AUC","Boyce"),
                                     parallel=T)
## Warnings ()
2: glm.fit: algorithm did not converge
3: glm.fit: fitted probabilities numerically 0 or 1 occurred
4: In lognet(xd, is.sparse, ix, jx, y, weights, offset, alpha,  ... :
  one multinomial or binomial class has fewer than 8  observations; dangerous ground ... (these messages repeat until 50)

Next function where the error appears:
EM.ESM.I.hoehnei<ecospat.ESM.EnsembleModeling(ESM.I.hoehnei,weighting.score='SomersD',threshold=0,models='all') 
################################
The following bivariate model(s) failed and are not included for building the ESMs
[1] "MAXENT.Phillips.2.ESM.BIOMOD.10" "MAXENT.Phillips.2.ESM.BIOMOD.11" "MAXENT.Phillips.2.ESM.BIOMOD.13" ... (continues)
################################
 The following bivariate model(s) is (are) not included for building the ESMs
 because evaluation score is smaller or equal to the given threshold of SomersD = 0 :
 [1] "GLM.ESM.BIOMOD.1"                "MAXENT.Phillips.2.ESM.BIOMOD.1"  "RF.ESM.BIOMOD.1"... (continues)
#### And the error message: 
Error in weighted.mean.default(x, weights[grep(models[i], names(weights))],  : 
  'x' and 'w' must have the same length
In addition: Warning messages:
1: In ecospat.ESM.EnsembleModeling(ESM.I.hoehnei, weighting.score = "SomersD",  :
  MAXENT.Phillips.2.ESM.BIOMOD.10MAXENT.Phillips.2 ... (continues)

I think that I've been getting this error because all of my models have Somers'D values lower than zero (that I set up as the threshold), but I don't know how to solve this (if there is a way). Someone can help me?

**Comment by diasthiago-93** [comment]
Hello. Any update on that? I'm having the same problem here

**Comment by FlavienCollart** [comment]
Hello, Thanks for your message and sorry for this long wait. This issue is now solved if you download the package from github. As we are still working on it, If you encounter any error. Please contact us.
