### ISSUE TITLE
Null hypothesis of niche equivalency test

### ISSUE THREAD

**Issue by SDMENM** [ecospat/ecospat#54]
Warren et al., 2010 : "the hypothesis of niche identity is rejected when the empirically observed value for I and/or D is significantly lower than the values expected from the pseudoreplicated data sets"

Hu J, Broennimann O, Guisan A, Wang B, Huang Y, Jiang J. Niche conservatism in Gynandropaa frogs on the southeastern Qinghai-Tibetan Plateau. Sci Rep. 2016 Sep 7;6:32624. doi: 10.1038/srep32624. PMID: 27601098; PMCID: PMC5013482
"The null hypothesis of niche equivalency is rejected when the observed values for similarity metrics are significantly different from the pseudoreplicated data sets"

What I understood from both the above papers is that if niche equivalency test turns out signficant (p<0.05) then we reject null hypothesis of niche equivalency, pharased differntly, two niches are not equivalent/identical. 
Ok, this makes sense so far, becasue equivalency test are usually significant most of the time (on my data).

Now, the Vignette of ecospat package says that "Niche equivalency test H1: the observed overlap between the native and invaded niche is higher than if the two niches are randomized, the niche expansion of the invaded niche is lower, the niche stability is
higher and the niche unfilling is lower than if the two niches are randomized", According to this, if the test turns out significant then we reject the null hypthesis, which I assume would be " both niches are as equiivalent as expected by chance" and if we reject this null, we conclude that niches are more equivalent than chance????

I got non-signifinat similarity test and a significant equivalency test for my data, does it mean that two niches are not more similar than by chance, but they are more equivalent than by chance??  what am i missing?? please help. Thanks in advance.

**Comment by ecospat** [comment]
the vignette is not up-to-date, sorry for that. Please refer to the help file of ecospat.niche.equivalency.test for an up-to-date description of the tests. We now leave it open to the user to define alternative hypothesis for the test, so you can test for niche equivalency or divergence depending on your needs.
