### ISSUE TITLE
"Error: Requesting more points (5) than available in cloud (4)"

### ISSUE THREAD

**Issue by ggrittz** [ecospat/ecospat#58]
Hello,

I'm getting the title error when using ```ecospat.occ.desaggregation```. My data is pretty simple (I'll upload it there).

I'm simply doing:
```
spp_all_coords2 <- ecospat.occ.desaggregation(xy = spp_all_coords,
                                              min.dist = 5000,
                                              by = "name")
```

```min.dist``` is meters, right?

Here's the data https://drive.google.com/file/d/19xLhjIKd-StBZLd4iTivW-ruoalsbjdX/view?usp=sharing

(I'm also not able to install the package via ```devtools::install_github()``` btw

Thanks!

**Comment by ecospat** [comment]
Hi, min.dist is in the units of the xy provided, so no, in your case it should be in decimal degrees.
for the installation of the package, have you tried 
install_github(repo="ecospat/ecospat/ecospat",ref="dev")
?

**Comment by ggrittz** [comment]
Hi, just updating you:

I went with https://github.com/ecospat/ecospat/blob/1e270f6644852e9f5a7fd4f52f9a8244ccc2f68d/ecospat/R/ecospat.occprep.R#L47 instead of ```nabor::knn``` and it worked after adjusting ```min.dist```. I'll try with ```nabor::knn``` later and, if anything weird happens I'll update here. Thanks.

Regarding GitHub, I was doing ```devtools::install_github("https://github.com/ecospat/ecospat")```. Thanks again.
