### ISSUE TITLE
Fix for broken function ecospat.niche.dynIndexProjGeo

### ISSUE THREAD

**Issue by plantarum** [ecospat/ecospat#59]
I would like to project the ecospat niche dynamic indices back into geographic space. You have the function `ecospat.niche.dynIndexProjGeo` that should serve this purpose. However, the code contains some bugs which produce erroneous results.

To demonstrate, here's an example:

```{R ecospat-data}
library(ecospat)
library(raster)
library(ade4)

data(ecospat.testNiche)
load(system.file("extdata", "ecospat.testEnvRaster.Rdata",
                 package="ecospat"))

xy.sp1 <- structure(c(556326.610512121, 559782.0917731,
            560785.296010159, 563683.441583884,
            567138.922844863, 564575.178683491,
            558110.084711336, 556438.077649571,
            571151.739793098, 567138.922844863,
            146746.555937794, 137651.144903364,
            130768.131147579, 124376.761231493,
            117002.103636009, 124991.316031117,
            136667.857223966, 137405.322983515,
            138019.877783138, 136176.213384267), dim =
            c(10L, 2L))
xy.sp2 <- structure(c(583301.657775252, 582632.854950547,
            582298.453538194, 581629.650713488,
            581183.782163684, 576056.29384094,
            582855.789225449, 581518.183576037,
            567250.389982314, 571263.206930549,
            130768.131147579, 129539.021548332,
            128924.466748708, 127941.17906931,
            127449.535229611, 119214.500914654,
            130276.48730788, 128555.733868934,
            136299.124344192, 137528.233943439), dim =
            c(10L, 2L))

plot(env[[1]])  
points(xy.sp1, pch = 21, bg = "green")
points(xy.sp2, pch = 21, bg = 2)
```

![starting-plot](https://user-images.githubusercontent.com/5727138/225670227-8eb17c3a-bf42-4e79-a86e-ff8945fdeb64.jpg)

This generates a simple system, with two species with nearly disjunct distributions in geographic space.

Now the niche dynamic index analysis:

```{R title}
env.sp1<-extract(env,xy.sp1)
env.sp2<-extract(env,xy.sp2)
env.bkg<-na.exclude(values(env))

pca.cal <- dudi.pca(env.bkg, center = TRUE, scale = TRUE, scannf = FALSE, nf = 2)
     
## predict the scores on the axes
scores.bkg <- pca.cal$li  
scores.sp1 <- suprow(pca.cal,env.sp1)$lisup
scores.sp2 <- suprow(pca.cal,env.sp2)$lisup

## calculation of occurence density (niche z)
z1 <- ecospat.grid.clim.dyn(scores.bkg, scores.bkg,
                            scores.sp1, R=100)
z2 <- ecospat.grid.clim.dyn(scores.bkg, scores.bkg,
                            scores.sp2, R=100)
ecospat.plot.niche.dyn(z1, z2)
points(scores.sp1, pch = 21, bg = "green")
points(scores.sp2, pch = 21, bg = 2)
```

![niche-plot](https://user-images.githubusercontent.com/5727138/225670786-9b6b1711-cbde-4cdd-905d-35e438c06f30.jpg)

The two species are nearly disjunct in environmental space as well, with a small area of 'stability'.

Now we can reproject the niche indices back to geographic space:

```{R reproject-bad}
geozS <- ecospat.niche.dynIndexProjGeo(z1, z2, env,
                                       index = "stability") 
geozE <- ecospat.niche.dynIndexProjGeo(z1, z2, env,
                                       index = "expansion")     
geozU <- ecospat.niche.dynIndexProjGeo(z1, z2, env,
                                       index = "unfilling")     

par(mfrow = c(1, 3))

plot(geozS, main="Stability", col = c("grey90", "blue"))
points(xy.sp1, pch = 21, bg = "green")
points(xy.sp2, pch = 21, bg = 2)

plot(geozE, main="Expansion", col = c("grey90", "red"))
points(xy.sp1, pch = 21, bg = "green")
points(xy.sp2, pch = 21, bg = 2)

plot(geozE, main="Unfilling", col = c("grey90", "green"))
points(xy.sp1, pch = 21, bg = "green")
points(xy.sp2, pch = 21, bg = 2)
```

![reproject-bad](https://user-images.githubusercontent.com/5727138/225681366-3f45c829-1823-48ac-b6ac-754afac44c07.jpg)

The niche indices don't appear to have any relationship to the observations in geographic space.

I looked into the code, and the primary problem is you are using the `$dyn` matrix returned from the function `ecospat.niche.dyn.index` to extract your niche indices. This matrix is rotated and flipped relative to the actual ordination space:

```{R compare-ordinations}
par(mfrow = c(1, 2))
plot(raster(ecospat.niche.dyn.index(z1,z2)$dyn),
     main = "ecospat.niche.dyn.index$dyn") 
ecospat.plot.niche.dyn(z1, z2, title = "es.plot.niche.dyn")
```

![compare](https://user-images.githubusercontent.com/5727138/225673732-e66032be-7f13-4cfd-8671-db38857a30c4.jpg)

Your code corrects the extent of the `$dyn` object, but it doesn't rotate it. Consequently, you scramble the niche index assignments. You have also switched the values for unfilling and expansion: in the `$dyn` object **1** indicates **unfilling**, and **-1** indicates **expansion**; this is reversed in `ecospat.niche.dynIndexProjGeo`.

To confirm this, I rewrote your function with to correct these issues:

```{R corrected}
tws.niche.dynIndexProjGeo <- function(z1, z2, env, index = "stability")
{
    XY <- rasterToPoints(env)[, 1:2]

    ## Rotate the category raster:
    ind <- t(ecospat.niche.dyn.index(z1,z2)$dyn)
    ind <- ind[nrow(ind):1, ]
    ind <- raster(ind)

    if (index == "stability") 
        ind <- ind == 2
    if (index == "unfilling") 
        ind <- ind == 1
    if (index == "expansion") 
        ind <- ind == -1
    if (index != "stability" & index != "unfilling" & index != 
        "expansion")
        stop("set index as stability,unfilling or expansion")
    ind@extent <- z1$z.uncor@extent
    ZS <- extract(ind, z1$glob)
    XYZS <- cbind(XY, ZS)
    geozS <- rasterFromXYZ(XYZS)
    return(geozS)
}

twsS <- tws.niche.dynIndexProjGeo(z1,z2,env,index="stability")
twsE <- tws.niche.dynIndexProjGeo(z1,z2,env,index="expansion")     
twsU <- tws.niche.dynIndexProjGeo(z1,z2,env,index="unfilling")     

par(mfrow = c(1, 3))

par(mfrow = c(1, 3))
plot(twsS, main="Stability", col = c("grey90", "blue"))
points(xy.sp1, pch = 21, bg = "green")
points(xy.sp2, pch = 21, bg = 2)

plot(twsE, main="Expansion", col = c("grey90", "red"))
points(xy.sp1, pch = 21, bg = "green")
points(xy.sp2, pch = 21, bg = 2)

plot(twsU, main="Unfilling", col = c("grey90", "green"))
points(xy.sp1, pch = 21, bg = "green")
points(xy.sp2, pch = 21, bg = 2)
```

![correct](https://user-images.githubusercontent.com/5727138/225681709-b581fc52-9950-4773-a568-4efbfe1da1ff.jpg)

Note that the `unfilling` category now shows the very clear pattern. It's less obvious in the `expansion` category.

Finally, I made another version that requires less code, and returns all three categories in a single raster:

```{R my-version}
tws.niche.dynIndexProjGeo2 <- function(z1, z2, env) {
  zRast <- 2*z1$w + z2$w
 
  ## We need **all** the cells from the env raster, even the
  ## NA ones. Those were removed in the example code above.
  
  ## all env cells:
  envVals <- values(env)[,1]

  ## index values for the non-NA cells:
  zCats <- extract(zRast, z1$glob)

  ## add index values to the non-NA cells:
  envVals[!is.na(envVals)] <- zCats 

  zCatRast <- env[[1]]
  values(zCatRast) <- envVals
  return(zCatRast)
}

tws2 <- tws.niche.dynIndexProjGeo2(z1,z2,env)     

plot(tws2, col = c("grey90", "red", "green", "blue"))
```

![myversion](https://user-images.githubusercontent.com/5727138/225675187-eaddcdd3-5e01-4f4d-8b65-b700314d6cb2.jpg)

I like my version better, but either this or my modified version of your function will produce the correct results.

**Comment by FlavienCollart** [comment]
Hello,

Sorry for the late answer. We'll try to have a look on this asap. Thank you for your help

**Comment by ecospat** [comment]
Hi Tyler, thanks for the debugging of the function! I checked your code, there was a rotation problem with $dyn indeed and your edits are all good to me. If you can send us a pull request that would be great! The version that produces one raster with the 3 niche dynamics categories would be most useful. Don't forget to modify the helpfile ecospat.niche.dynIndexProjGeo.Rd and add your name in the author field! cheers, Olivier
