### ISSUE TITLE
Issue with Calibration of ESM model

### ISSUE THREAD

**Issue by sunmck** [ecospat/ecospat#63]
I want to model a species distribution of an invasive species using an ESM model. I formatted the data using `BIOMOD_FormatingData()`, with sampling of pseudo-absence points of the species. However, when calibrating the ESMs, I get the following error:

`Checking Cross-Validation arguments...
Error in .bm_CrossValidation.check.args(bm.format = bm.format, strategy = strategy,  : 
  perc (or CV.perc) is required when strategy = 'random'`

The parameter `CV.perc` belongs to the function `BIOMOD_Modeling()` which I am not manipulating directly. Do you have an idea why this error is occurring?

Here is the full code:
```
inv.biomod <- BIOMOD_FormatingData(resp.var = inv[,23],
                                   PA.strategy = "random", # pseudo absence selection necessary because only occurrence and no absence data is available
                                   PA.nb.rep = 1, 
                                   PA.nb.absences = 1000, 
                                   expl.var = bio_aus, # bioclim data
                                   resp.xy = inv.coords,
                                   resp.name = "Oryctolagus cuniculus")
plot(inv.biomod)

# Calibration of simple bivariate models
inv.ESM <- ecospat.ESM.Modeling(data = inv.biomod,
                                models = c('GLM'),
                                NbRunEval = 2,
                                DataSplit = 70,
                                weighting.score = c('AUC'),
                                parallel = F)

# Ensemble models
inv.ESM.ens <- ecospat.ESM.EnsembleModeling(inv.ESM, 
                                           weighting.score = c("SomersD"), 
                                           threshold = 0)

```

**Comment by FlavienCollart** [comment]
Hello,

This issue is present with biomod2 v.4.2-3. Please try to install biomod v4.2-2 instead. We are currently working to adapt our functions to this new update of biomod2 package.

Best,

Flavien

**Comment by sunmck** [comment]
Thanks a lot, problem solved. Kind regards!

**Comment by sunmck** [comment]
At least I though so... Now I get the following Error when using `ecospat.ESM.ensemble()`:

```
> # Projection of calibrated ESMs into new space or time
> nat.ESM.ens_proj_current <- ecospat.ESM.EnsembleProjection(ESM.prediction.output = nat.ESM_proj_current,
+                                                            ESM.EnsembleModeling.output = nat.ESM.ens,
+                                                            chosen.models = 'all')
Error in ecospat.ESM.EnsembleProjection(ESM.prediction.output = nat.ESM_proj_current,  : 
  object 'string_pred' not found
```

This is my complete code for modelling the ESMs:


```
# format data using the biomod2 package
ocEUR$occ <- 1
ocEUR_coords <- data.frame(coordinates(ocEUR))

nat.biomod <- BIOMOD_FormatingData(resp.var = as.numeric(data.frame(ocEUR)[,23]),
                                   PA.strategy = "random", # pseudo absence selection necessary because only occurrence and no absence                                       data is available
                                   PA.nb.rep = 1, # number of repetitions of pseudo-absence points that are drawn
                                   PA.nb.absences = 1000, # number of pseudo-absence points that will be selected
                                   expl.var = wclim, # RasterStack of global environmental data 
                                   resp.xy = ocEUR_coords,
                                   resp.name = "Oryctolagus cuniculus")

biomodopt <- bm_DefaultModelingOptions()

# Calibration of simple bivariate models
nat.ESM <- ecospat.ESM.Modeling(data = nat.biomod,
                                models = c('GLM'),
                                NbRunEval = 2,
                                DataSplit = 70,
                                weighting.score = c("AUC"),
                                models.options = biomodopt)

# Ensemble models
nat.ESM.ens <- ecospat.ESM.EnsembleModeling(nat.ESM, 
                                            weighting.score = c("SomersD"), 
                                            threshold = 0)

# Projection of simple bivariate models into new space or time
nat.ESM_proj_current <- ecospat.ESM.Projection(ESM.modeling.output = nat.ESM,
                                               new.env = wclim)

# Projection of calibrated ESMs into new space or time
nat.ESM.ens_proj_current <- ecospat.ESM.EnsembleProjection(ESM.prediction.output = nat.ESM_proj_current,
                                                           ESM.EnsembleModeling.output = nat.ESM.ens,
                                                           chosen.models = 'all')
```

Do you have an idea what the cause of this error could be? What is the object `string_pred` and where should it be located?

**Comment by FlavienCollart** [comment]
Hello,

"string_pred" only appears when projecting using data.frame. Can you check if wclim is a RasterStack (and not a RasterBrick)? If it is a rasterBrick, then you'll have to redo the projections and then the ensemble Projection. But if you do not want to run again the projections AND if in the diverse folder you have ".tif" files, yo can modify the object nat.ESM_proj_current by doing this:

nat.ESM_proj_current$new.env.raster = TRUE

Hope it will help you.

Best,

Flavien

**Comment by sunmck** [comment]
I tried RasterStack, dataframe and matrix for the `new.env` parameter but all lead to the same error message... Should I send you the entire code?

**Comment by FlavienCollart** [comment]
Hi again,

I've run your script and it works well for me but I had to add two more lines (see below) as when you crop rasterStack, they change into RasterBrick and our package do not deal with that. Here are the changes
in L171: eurEnvR <- stack(eurEnvR)
and in L196: ausEnvR <- stack(ausEnvR)
and you can also remove L202, which is not useful if you add L171 and 196
Here is the final output:
![ESM_Australia](https://github.com/ecospat/ecospat/assets/46991874/f04cf858-977b-4b31-b4c3-e4ea0903eb59)

**Comment by sunmck** [comment]
The code still doesn't run for me. Can you send us a list of your installed package versions?

**Comment by FlavienCollart** [comment]
Here are the version of the dependencies package:
                      Package                 Version
ade4                  "ade4"                  "1.7-22"
adehabitatHR          "adehabitatHR"          "0.4.21"
adehabitatMA          "adehabitatMA"          "0.3.16"
alphahull             "alphahull"             "2.5"
ape                   "ape"                   "5.7-1" 
classInt              "classInt"              "0.4-9"
biomod2               "biomod2"               "4.2-2"  
dismo                 "dismo"                 "1.3-14"  
ecodist               "ecodist"               "2.0.9" 
foreach               "foreach"               "1.5.2" 
gtools                "gtools"                "3.9.4"
Hmisc                 "Hmisc"                 "5.1-0"
igraph                "igraph"                "1.3.5" 
knitr                 "knitr"                 "1.42" 
ks                    "ks"                    "1.14.0"  
maps                  "maps"                  "3.4.1"
maptools              "maptools"              "1.1-6"
markdown              "markdown"              "1.4"
matrixStats           "matrixStats"           "0.63.0"
nabor                 "nabor"                 "0.5.0"  
poibin                "poibin"                "1.5"
PresenceAbsence       "PresenceAbsence"       "1.1.11"
qpdf                  "qpdf"                  "1.3.0"     
randomForest          "randomForest"          "4.7-1.1"   
raster                "raster"                "3.6-20"  
rgdal                 "rgdal"                 "1.6-2"  
rgeos                 "rgeos"                 "0.5-9" 
rJava                 "rJava"                 "1.0-6" 
rms                   "rms"                   "6.3-0" 
snowfall              "snowfall"              "1.84-6.2" 
sp                    "sp"                    "1.6-0"
terra                 "terra"                 "1.7-29" 
vegan                 "vegan"                 "2.6-4" 
XML                   "XML"                   "3.99-0.13"

**Comment by FlavienCollart** [comment]
Can you try to update the dependencies of ecospat? If it is still not working, I won't be able to correct the issue as I cannot generate the issue

**Comment by FlavienCollart** [comment]
By the way, I did all the tests in R v4.2.2. What is your R version ?

**Comment by sunmck** [comment]
Are you also using ecospat 3.5?

**Comment by FlavienCollart** [comment]
I use the version from github (v.3.5.1). ecospat v.3.5 had some code issues that I have corrected in the one from github, regarding ESM functions. Thus, try to download this version using: 
require(devtools)
install_github("ecospat/ecospat/ecospat") 

Hopefully it will work and sorry to not see this package version difference

**Comment by sunmck** [comment]
Oh, with the github version the function runs at least, returning a new error `Error in .local(x, w, ...) : length(w) == nlayers(x) is not TRUE`. All other package versions and R are the same.

**Comment by sunmck** [comment]
So, we finally got it running with the github version of ecospat. Thanks a lot for the support, we really appreciated it!
