### ISSUE TITLE
error message because of more number of models in ESM modeling

### ISSUE THREAD

**Issue by nihalk84** [ecospat/ecospat#64]
Hello,

I have been trying to cope with ESM modeling for more than one week. I have a data frame with a low occurrence number of one plant species. So, the Ensemble of Small Models was suggested. I have received many errors within this period (see https://github.com/biomodhub/biomod2/issues/262).
Finally, I and one of the biomod2 team members decided to use the version biomod2 4.2-2 with the current ecospat 3.5. It was working until ecospat.ESM.Modeling function with two or more models [models=c('GLM','RF')]. I also checked it with the package examples (https://rdrr.io/cran/ecospat/man/ecospat.ESM.Modeling.html). It worked with one model but it did not work with two or more models in the function ecospat.ESM.Modeling, as well. The error message below:
> my.ESM_EF <- ecospat.ESM.EnsembleModeling(my.ESM,weighting.score=c("SomersD"),threshold=0)
Error in x.calib[row, NbRunEval + 1] : incorrect number of dimensions

Second, when I use one model (GLM or RF), I received another error in the function of ecospat.ESM.EnsembleProjection below:
> my.ESM_EFproj_current <- ecospat.ESM.EnsembleProjection(ESM.prediction.output=my.ESM_proj_current_n, ESM.EnsembleModeling.output=my.ESM_EF_n)
Error in ecospat.ESM.EnsembleProjection(ESM.prediction.output = my.ESM_proj_current_n,  : 
  object 'string_pred' not found

Thank you.

**Comment by FlavienCollart** [comment]
Hello,

This issue has been corrected in the github version of the package. Please try to install this package version. For now, it is only working with biomod2 v. 4.2-2

Do not hesitate to contact us if you encounter any issues.

Best,

Flavien
