### ISSUE TITLE
Ask a question about multispecies

### ISSUE THREAD

**Issue by 675979649** [ecospat/ecospat#71]
Recently I have been doing research on ecological niches, and we had an idea:
In this article, ecospat analysis of two sister species is presented (doi: 10.1111/ecog.02671). We now have a stem-boring pest and its host, can the ecospat package reasonably analyze the overlapping ecological niches of the host and its pests?

**Comment by FlavienCollart** [comment]
Hello,
the function ecospat.niche.overlap could work. The method is describe in Broennimann et al (2012; https://doi.org/10.1111/j.1466-8238.2011.00698.x) and you can check the manual to understand how you can use the function.
