### ISSUE TITLE
Malfunctioning in some functions

### ISSUE THREAD

**Issue by HumbertoNappo** [ecospat/ecospat#77]
I have a script in which I use a lot of ecospat functions. Everything worked fine until the last time I worked with it (May 2023). However, yesterday I tried to run the code again to render a quarto pdf and some ecospat functions are returning errors. I am using ecospat 4.0.0 and R 4.3.1 on a Windows 10 PC.

`> ecospat.plot.niche(grid_clim_nat)`
`> Error in image.default(x = z$x, y = z$y, z = t(terra::as.matrix(z$z.uncor,  : no slot of name "pnt" for this object of class "SpatRaster"`

For ecospat.plot.niche, changing @pnt to @cpp in the function solves the problem.

`> ecospat.niche.similarity.test(grid_clim_nat, grid_clim_inv, rep = 1000, overlap.alternative = "higher", rand.type = 2,  ncores = detectCores() - 1)`

`> Error in checkForRemoteErrors(val) :  3 nodes produced errors; first error: NULL value passed as symbol address`

`> ecospat.plot.niche.dyn(grid_clim_nat, grid_clim_inv, interest = 2, name.axis1 = "PC1", name.axis2 = "PC2", col.unf = "green", col.exp = "red", col.stab = "blue", colZ1 = "green", colZ2 = "red")`
`> Error in h(simpleError(msg, call)) :  error in evaluating the argument 'x' in selecting a method for function 'sort': error in evaluating the argument 'x' in selecting a method for function 'unique': [+] extents do not match`

**Comment by bjohnso005** [comment]
I am also receiving "Error in image.default(x = z$x, y = z$y, z = t(terra::as.matrix(z$z.uncor,  : 
  no slot of name "pnt" for this object of class "SpatRaster" messages when using ecospat.plot.niche() and agree with Humberto to change @pnt to @cpp

**Comment by HumbertoNappo** [comment]
> I am also receiving "Error in image.default(x = z$x, y = z$y, z = t(terra::as.matrix(z$z.uncor, : no slot of name "pnt" for this object of class "SpatRaster" messages when using ecospat.plot.niche() and agree with Humberto to change @pnt to @cpp

Do `ecospat.niche.similarity.test()` and `ecospat.plot.niche.dyn()` work for you?

**Comment by bpetitpi** [comment]
Thank you for your feedbacks. We are working to fix this issue !

**Comment by bpetitpi** [comment]
The `ecospat.plot.niche()` issue should be solved now (see the code int the dev branch). 

> Do `ecospat.niche.similarity.test()` and `ecospat.plot.niche.dyn()` work for you?

Could you tell me if the error also arises with the data of the vignette? I don't get any error on my side. If not could you provide a reproducible example of your error?

**Comment by LuisEnriqueAngelesGonzalez** [comment]
Hello, I am having the same error when I specify rand.type = 2. Will my analyis of invasive species would be wrong if I use rand.type = 1?

**Comment by HumbertoNappo** [comment]
Running the code again, `ecospat.plot.niche.dyn()` is working just fine (I may have messed something up the last time). However, as posted by Luis, the error message in `ecospat.niche.similarity.test()` only appears when `rand.type = 2`. Changing this option would be prejudicial to the analysis? GitHub does not support .RData files so I can't send you the files necessary to replicate the bug here. Maybe I can send you this R objects by email?

**Comment by bjohnso005** [comment]
I can confirm `ecospat.plot.niche()` is working again using the dev branch.
I can also confirm setting `rand.type = 2` within `ecospat.niche.similarity.test()` is not working, but I get a different error message than Luis. I get the error message : `Error in p1 - p2 : non-conformable arrays` with my own data. This is reproducible in the vignette by changing the parameter in Line 221 of vignette_ecospat_package.Rmd, which output the same error message.

**Comment by FlavienCollart** [comment]
Hello,
Thank you for your message. Indeed, there is an error when rand.type = 2. We are working to fix this issue

**Comment by carla2908** [comment]
Hello! I am having the error that seems to have been solved (Error in image.default(x = z$x, y = z$y, z = t(terra::as.matrix(z$z.uncor,  : 
  no slot of name "pnt" for this object of class "SpatRaster") when using ecospat.plot.niche function. Where can I find the solution to fix it? Thank you very much!!

**Comment by carla2908** [comment]
additionally, when I use the ecospat.grid.clim.dyn function I get the following error but for only one of my species - 

Error in quantile.default(terra::extract(x.dens, x)[, 1], th) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

Any feedback will be greatly appreciated.
Thanks!

**Comment by danlwarren** [comment]
Really glad I found this!  I think this may be related to some issues we're having with ecospat and ENMTools right now as well.

**Comment by FlavienCollart** [comment]
Hello,

The issue when rand.type = 2 has been corrected. Please try it by downloading our dev version:
devtools::install_github("ecospat/ecospat/ecospat@dev") 
Let me know if the issue has been corrected.

**Comment by danlwarren** [comment]
Tried it just now and I got an error.  Here's the traceback:

<img width="793" alt="image" src="https://github.com/ecospat/ecospat/assets/3770891/e8cce92d-8f6b-4e5f-82ef-51091e7beb28">

**Comment by danlwarren** [comment]
Seems to be working now, thank you!

**Comment by FlavienCollart** [comment]
Perfect!
