### ISSUE TITLE
Error with failing models in ecospat.ESM.EnsembleModeling

### ISSUE THREAD

**Issue by JeMaNd-r** [ecospat/ecospat#79]
I'm successfully building ESMs with the `ecospat.ESM.Modeling` function (GLM and MAXENT). Some of the individual ESMs fail, but there majority doesn't. However, when trying to run `ecospat.ESM.EnsembleModeling` for some of my species, I get this error message: 

```
All GLM models failed for ESM.BIOMOD.36Error in apply(x, 1, mean, na.rm = TRUE) : 
  dim(X) must have a positive length
In addition: Warning message:
In FUN(X[[i]], ...) : 
```
I see that it can't process because some of the files it expects to be there are missing (failed ESMs) and that this might be a hind for the user to check the models. But the GLM works in the 35 other ESMs (and more), so I would like to simply ignore the failed ones, but not all of the GLMs (so not with the models argument in the function).

I didn't find a way to **tell the function to "ignore" these failed ESMs**. The function actually does already ignore failed individual models, right? So it only seem to have an issue(?) with ESMs where all the models (of one algorithm) failed.

In the case of this ESM.BIOMOD.36, the ESM.modeling.output looks like this:

```
$mymodels[[36]]

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.models.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Modeling folder : .

Species modeled : ESM.BIOMOD.36

Modeling id : Entom_schoe_Modeling

Considered variables : PCA_6 PCA_7


Computed Models :  ESM.BIOMOD.36_PA1_RUN1_MAXENT ESM.BIOMOD.36_PA1_RUN2_MAXENT ESM.BIOMOD.36_PA1_RUN3_MAXENT 
ESM.BIOMOD.36_PA1_RUN4_MAXENT ESM.BIOMOD.36_PA1_RUN5_MAXENT ESM.BIOMOD.36_PA1_RUN6_MAXENT ESM.BIOMOD.36_PA1_RUN7_MAXENT 
ESM.BIOMOD.36_PA1_RUN8_MAXENT ESM.BIOMOD.36_PA1_RUN9_MAXENT ESM.BIOMOD.36_PA1_RUN10_MAXENT ESM.BIOMOD.36_PA1_allRun_MAXENT 
ESM.BIOMOD.36_allData_allRun_MAXENT


Failed Models :  ESM.BIOMOD.36_PA1_RUN1_GLM ESM.BIOMOD.36_PA1_RUN2_GLM ESM.BIOMOD.36_PA1_RUN3_GLM ESM.BIOMOD.36_PA1_RUN4_GLM 
ESM.BIOMOD.36_PA1_RUN5_GLM ESM.BIOMOD.36_PA1_RUN6_GLM ESM.BIOMOD.36_PA1_RUN7_GLM ESM.BIOMOD.36_PA1_RUN8_GLM ESM.BIOMOD.36_PA1_RUN9_GLM 
ESM.BIOMOD.36_PA1_RUN10_GLM ESM.BIOMOD.36_PA1_allRun_GLM ESM.BIOMOD.36_allData_allRun_GLM
```
Versions I'm using: ecospat_4.0.0 and biomod2_4.2-4.     

**Is there a workaround for this? Or are you already working on this?** 

And may I also ask you to specify the models argument in the `ecospat.ESM.EnsembleModeling` function? It is not fully clear what input is expected there: only character (e.g. "GLM") or the full model name like in the respective biomod2 argument models.chosen.

**Comment by FlavienCollart** [comment]
Hello,

Normally ecospat.ESM.EnsembleModeling removed failed models except if an algorithm fail totally for all the possible combination of variables. If so, then, you can simply remove these models when making the ensemble. In your case, as GLM failed, you can only make the ensemble based on maxent:

ecospat.ESM.EnsembleModeling( ESM.modeling.output, 
                                  weighting.score, 
                                  threshold=NULL, 
                                  **models = c("MAXENT")**)

**Comment by FlavienCollart** [comment]
Hello,

normally our code can deal with that, can you send me your data + code so that I can produce the issue.

**Comment by JeMaNd-r** [comment]
Sure! 

The model output is too big to upload everything here, so I selected the Model.Output file and the one from one of the models (number 40), where all GLMs failed. Not sure if you can use it without the actual folders, but just in case. Models were all GLMs failed are 36-38, 40 and 43. It doesn't seems to be an issue with the Predictors (they are different in these models and work in others).

[Code_and_data.zip](https://github.com/ecospat/ecospat/files/13364321/Code_and_data.zip)
[Model_output.zip](https://github.com/ecospat/ecospat/files/13364358/Model_output.zip)

**Comment by FlavienCollart** [comment]
Hello,
I've found the issue and I corrected it. Normally, it should work if you download the dev version of our package using this code line:
devtools::install_github("ecospat/ecospat/ecospat@dev")

Let me know if it works now.

Cheers,

Flavien

**Comment by JeMaNd-r** [comment]
Yes! It works. Thank you 😄
