### ISSUE TITLE
possible typo in ecospat.grid.clim.dyn

### ISSUE THREAD

**Issue by edgagnon** [ecospat/ecospat#8]
Having been trying to run this function, using a pca built on a different backgrounds that contains a subsample of the available space (i'm comparing different growth forms on a worlwide scale, at 30'arcsec resolution). Testing how ecospat niche equivalency and similarity tests behave by limiting myself to Madagascar at the moment.

I kept getting the following mistake for the function ecospat.grid.clim.dyn: 
Error in quantile.default(glob1r, th.env) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

I think the source of my error is this, on line 133.
glob1r <- extract(glob1.dens, glob1) 

Could the correction for this line be:
glob1r <- extract(glob1.dens, **glob1r)** 

Thanks for your help.

**Comment by edgagnon** [comment]
Actually, this was not the problem, sorry for bothering you!

**Comment by edixon1** [comment]
I am now experiencing the same problem you mentioned above.  Did you find a resolution?

**Comment by Zeroo11** [comment]
> 

Hello，
I also encountered the same error: missing values and NaN's not allowed if 'na.rm' is FALSE

How did you solve it?
Looking forward to your reply, thanks!

**Comment by SDMENM** [comment]
> > 
> 
> Hello， I also encountered the same error: missing values and NaN's not allowed if 'na.rm' is FALSE
> 
> How did you solve it? Looking forward to your reply, thanks!


Hello, were you able to find any solution?? Only equivalency tests give me error missing values and NaN's not allowed if 'na.rm' is FALSE
