### ISSUE TITLE
no slot for "pnt" 

### ISSUE THREAD

**Issue by SDMENM** [ecospat/ecospat#81]
ecospat.plot.nich function throws me this error "Error in image.default(x = z$x, y = z$y, z = t(terra::as.matrix(z$z.cor,  : 
  no slot of name "pnt" for this object of class "RasterLayer" 
Any idea what am I doing wrong? I am not using rasters, rather swd files with coordinates and attributes. 

Thanks.

**Comment by FlavienCollart** [comment]
Hello,

Can you try the dev version of our package (devtools::instal_github("ecospat/ecospat/ecospat@dev")). If the error persists, please send us your script to see what's wrong.

Have a great day,

Flavien
