### ISSUE TITLE
Boyce issue no longer working for spatrasters

### ISSUE THREAD

**Issue by knussear** [ecospat/ecospat#83]
Recent update returns error for continuous boyce index. Results in "Error in seq.default(from = mini, to = maxi - window.w, by = (maxi - mini -  : 
  'from' must be of length 1"

**Comment by FlavienCollart** [comment]
Hello,
I've found the bug and normally corrected it. Please try again by installing the dev version of our package: devtools::install_github("ecospat/ecospat/ecospat@dev")

Let me know if it works now
