### ISSUE TITLE
The ecospat.ESM.EnsembleProjection issues

### ISSUE THREAD

**Issue by woaichixuegao** [ecospat/ecospat#84]
### Projection of simple bivariate models into new space 
> my.ESM_proj_current<-ecospat.ESM.Projection(ESM.modeling.output=my.ESM,
+                                             new.env=myExpl,
+                                             name.env="current")
> ### Projection of calibrated ESMs into new space 
> my.ESM_EFproj_current <- ecospat.ESM.EnsembleProjection(ESM.prediction.output=my.ESM_proj_current,
+                                                         ESM.EnsembleModeling.output=my.ESM_EF,
+                                                         chosen.models = c('GLM','GAM','RF','MARS','MAXENT'))
Error in gzfile(file) : invalid 'description' argument

**Comment by FlavienCollart** [comment]
Hello,
can you send us your script and also the list of your packages with their versions?

**Comment by woaichixuegao** [comment]
Dear Flavien Collart ,

I trust this message finds you well. I am writing to seek your expertise regarding an error I have encountered while working on the ESM ensemble projection. The code snippet I have used is as follows:
my.ESM_proj_current<-ecospat.ESM.Projection(ESM.modeling.output=my.ESM, new.env=myExpl, name.env="current") Projection of calibrated ESMs into new space my.ESM_EFproj_current <- ecospat.ESM.EnsembleProjection(ESM.prediction.output=my.ESM_proj_current, ESM.EnsembleModeling.output=my.ESM_EF, chosen.models = c('GLM','GAM','RF','MARS','MAXENT')) Error in gzfile(file) : invalid 'description' argument

My Biomod2 version 4.2.5, Ecospat version 4.0. The script as follow:

library(biomod2) library(xlsx) library(raster) library(ecospat) myRespName <- 'S' DataSpecies <- read.csv('S.csv') myResp <- as.numeric(DataSpecies[,myRespName]) myRespXY <- DataSpecies[, c("longitude","latitude")] files <- list.files(path=paste("current", sep=''), pattern='asc', full.names=TRUE) myExpl = stack(files) myBiomodData <- BIOMOD_FormatingData( resp.var = myResp, expl.var = myExpl, resp.xy = myRespXY, resp.name = myRespName, PA.nb.rep = 1, # PA.nb.absences = 10000, # PA.strategy = 'random' ) my.ESM <- ecospat.ESM.Modeling( data=myBiomodData, models=c('GLM','GAM','RF','MARS','MAXENT'), NbRunEval=5, DataSplit=75, weighting.score=c("AUC"), parallel=FALSE) my.ESM_EF <- ecospat.ESM.EnsembleModeling(my.ESM,weighting.score=c("SomersD"),threshold=0) ### thresholds to produce binary maps my.ESM_thresholds <- ecospat.ESM.threshold(my.ESM_EF) ### Evaluation of bivariate and ensemble models based on standard cross-validation my.ESM_EF$ESM.evaluations my.ESM_thresholds ### Evaluation of the ensemble models based on the pooling procedure my.ESM_evaluations <- ecospat.ESM.EnsembleEvaluation(ESM.modeling.output= my.ESM, ESM.EnsembleModeling.output = my.ESM_EF, metrics= c("AUC","MaxTSS"), EachSmallModels = FALSE) my.ESM_evaluations$ESM.evaluations ### Projection of simple bivariate models into new space my.ESM_proj_current<-ecospat.ESM.Projection(ESM.modeling.output=my.ESM, new.env=current) ### Projection of calibrated ESMs into new space my.ESM_EFproj_current <- ecospat.ESM.EnsembleProjection(ESM.prediction.output=my.ESM_proj_current, ESM.EnsembleModeling.output=my.ESM_EF) ### Binary Projection based on max TSS of calibrated ESMs into new space my.ESM_EFproj_current_binary <- (my.ESM_EFproj_current > (my.ESM_thresholds$TSS.th*1000))*1 ## get the variable contributions of ESMs ecospat.ESM.VarContrib(my.ESM,my.ESM_EF)

I have reviewed the code, but I am unable to identify the source of this error. Your guidance on resolving this issue would be highly appreciated.




Best regards,

Xiang Zhao

The Institute of Plant Protection (IPP), Chinese Academy of Agricultural Sciences (CAAS)










在 2024-01-18 23:50:12，"FlavienCollart" ***@***.***> 写道：

Hello,
can you send us your script and also the list of your packages with their versions?

**Comment by FlavienCollart** [comment]
Hello,
Maybe the error is due to the use of raster package instead of terra package. ecospat package is not working with raster package anymore. I thus think that the individual projections were not generated. Please check my.ESM_proj_current$pred.biva is empty or contains file names in ".tif". If it is empty, please try again to run **ecospat.ESM.Projection** but by changing the object "current" (which was werdly not defined in your script but I guess is similar to the RasterStack "myExpl") to a **SpatRaster** using the rast function from the terra package. And then run  ecospat.ESM.EnsembleProjection

**Comment by woaichixuegao** [comment]
Hello，
    Thanks a lot，I try again！

---- Replied Message ----
| From | ***@***.***> |
| Date | 01/20/2024 21:35 |
| To | ecospat/ecospat ***@***.***> |
| Cc | woaichixuegao ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ecospat/ecospat] The ecospat.ESM.EnsembleProjection issues (Issue #84) |

Hello,
Maybe the error is due to the use of raster package instead of terra package. ecospat package is not working with raster package anymore. I thus think that the individual projections were not generated. Please check my.ESM_proj_current$pred.biva is empty or contains file names in ".tif". If it is empty, please try again to run ecospat.ESM.Projection but by changing the object "current" (which was werdly not defined in your script but I guess is similar to the RasterStack "myExpl") to a SpatRaster using the rast function from the terra package. And then run ecospat.ESM.EnsembleProjection

**Comment by woaichixuegao** [comment]
My problem is solved, thanks for the answer!
















At 2024-01-20 21:38:57, "赵浩翔" ***@***.***> wrote:

Hello，
    Thanks a lot，I try again！

---- Replied Message ----
| From | ***@***.***> |
| Date | 01/20/2024 21:35 |
| To | ecospat/ecospat ***@***.***> |
| Cc | woaichixuegao ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ecospat/ecospat] The ecospat.ESM.EnsembleProjection issues (Issue #84) |

Hello,
Maybe the error is due to the use of raster package instead of terra package. ecospat package is not working with raster package anymore. I thus think that the individual projections were not generated. Please check my.ESM_proj_current$pred.biva is empty or contains file names in ".tif". If it is empty, please try again to run ecospat.ESM.Projection but by changing the object "current" (which was werdly not defined in your script but I guess is similar to the RasterStack "myExpl") to a SpatRaster using the rast function from the terra package. And then run ecospat.ESM.EnsembleProjection

**Comment by FlavienCollart** [comment]
Perfect! Happy to read that your problem is solved.
