### ISSUE TITLE
"Error occurs at p1 - p2: non-conformable arrays." showed up in ecospat.niche.similarity.test when rand=2

### ISSUE THREAD

**Issue by JuiTse** [ecospat/ecospat#85]
Dear colleagues, 
When I follow the working code in the webpage and the vignette of ecospat : 
https://rsh249.github.io/spatial_bioinformatics/niche_overlap.html?fbclid=IwAR3BapgUiVaoXN6whezxWBfZ6rxS1PmP2-h7zIdhH7n6OZD3wwxGkB1pIPs

I just come across the issue  "Error occurs at p1 - p2: non-conformable arrays." in function ecospat.niche.similarity.test using the following code with randomization type=2:
sim.test_RK <- ecospat.niche.similarity.test(grid.clim1, grid.clim2, rep=100, 
							overlap.alternative = "higher",
							expansion.alternative = "lower",
							stability.alternative = "higher",
							unfilling.alternative = "lower",
							intersection = NA,
							rand.type=2) 
When looking into the source code, seems like the z1 in "o.i <- ecospat.niche.overlap(z1, z2.sim, cor = TRUE)"  cause the problem, but I can not figure it out. 

BTW, I successfully calculated the ecospat.niche.overlap, ecospat.niche.equivalency.test, and even ecospat.niche.similarity.test when randomization type=1, as follows:
scores.globclim <- readRDS("scores.globclim.rds")
scores.AK <- readRDS("scores.AK.rds")
scores.AR <- readRDS("scores.AR.rds")
scores.wAK <- readRDS("scores.wAK.rds")
scores.wAR <- readRDS("scores.wAR.rds")

#Occurence density grid
grid.clim1 <- ecospat.grid.clim.dyn(
  glob = scores.globclim,
  glob1 = scores.wAK,
  sp = scores.AK,
  R = 100,
  th.sp = 0
)

grid.clim2 <- ecospat.grid.clim.dyn(
  glob = scores.globclim,
  glob1 = scores.wAR,
  sp = scores.AR,
  R = 100,
  th.sp = 0
)

#Schoener's D
D.overlap <- ecospat.niche.overlap (grid.clim1, grid.clim2, cor=T)$D 
D.overlap

#Warren's I (should be Hellinger's I)
I.overlap <- ecospat.niche.overlap (grid.clim1, grid.clim2, cor=T)$I
I.overlap

#Niche Equivalency
eq.test <- ecospat.niche.equivalency.test(grid.clim1, grid.clim2, rep=100, intersection=NA, 
							overlap.alternative="higher",
							expansion.alternative="lower",
							stability.alternative="higher",
							unfilling.alternative="lower")

#Niche Similarity Test
sim.test_KR <- ecospat.niche.similarity.test(grid.clim1, grid.clim2, rep=100, 
							overlap.alternative = "higher",
							expansion.alternative = "lower",
							stability.alternative = "higher",
							unfilling.alternative = "lower",
							intersection = NA,
							rand.type=1) 

Please give me some hints about this issues, thank you. 
What I would like to know is the niche similarity when compare A to B and B to A.
Such as:
ecospat.niche.similarity.test(grid.clim1, grid.clim2, ...,rep=100, rand.type=2)
v.s.
ecospat.niche.similarity.test(grid.clim2, grid.clim1, ...,rep=100, rand.type=2)

Really appreciate your help, 
Best regards, 
Jui-Tse

[askQ.zip](https://github.com/ecospat/ecospat/files/14006975/askQ.zip)

**Comment by JuiTse** [comment]
BTW, I am using R version 4.3.2 and ecospat v4.0.0

**Comment by JuiTse** [comment]
Hi, everything work well when I try the older version 3.5.1.
So it seems like some bugs inside the version 4.0.0.

But anyway, I successfully get the results.

**Comment by FlavienCollart** [comment]
Hello,

Please try to download our dev version by running:
devtools::install_github("ecospat/ecospat/ecospat@dev"

The problem is normally corrected.
