### ISSUE TITLE
ecospat.niche.similarity.test - Error: [ext] expected four numbers

### ISSUE THREAD

**Issue by carla2908** [ecospat/ecospat#88]
Hi!

I have been trying to run the similarity function but I get the following error:
**Error: [ext] expected four numbers**

sim1<-ecospat.niche.similarity.test(z1,z2,rep=100, intersection = NA,
                                    overlap.alternative = "higher",rand.type = 1)

May I have a hint of what might be going wrong? I installed the package using the code below:
devtools::install_github("ecospat/ecospat/ecospat@dev")

Thanks!
Carla

**Comment by FlavienCollart** [comment]
Hello,

we corrected the issue. Please try again by installing the dev version

Cheers,
Flavien
