### ISSUE TITLE
Changing R in ecospat.grid.clim.dyn leads to unexpected raster dimensions

### ISSUE THREAD

**Issue by aniruddhamarathe** [ecospat/ecospat#89]
Hi,

I noticed that any value of R apart from the degault 100, leads to unexpected dimensions in the raster output of the climate grid. I was able to track this issue to the line 91 of 'ecospat.nichedynamic.R'. Here, while making a spatraster from x.dens$ud the nrow argument is hard coded to 100, which calculates the ncols depending on the number of pixels. So, the result is not a RxR raster. 

Thank you.

**Comment by FlavienCollart** [comment]
Hi,

Thanks for reporting this issue. We saw this bug two weeks ago and change it in the dev version. Please try it by running: 
devtools::install_github("ecospat/ecospat/ecospat@dev")

**Comment by aniruddhamarathe** [comment]
Thank you for your response. I wil load the github version.
