### ISSUE TITLE
Don't work histogram

### ISSUE THREAD

**Issue by Kazuya-Haganuma** [ecospat/ecospat#92]
Dear `ecospat` team,

Hello.
I was studying Ecological Niche modeling and tried to run `ecospat.cor.plot` using by "tabular/bioclim/current/bioclim_table.csv" that was in [this page](https://github.com/hsdm-hub/hsdm)'s data file.

I expected the following.
<img width="633" alt="スクリーンショット 2024-04-04 20 12 21" src="https://github.com/ecospat/ecospat/assets/99643952/59aaa5cc-3bda-46e4-a9a8-e204d0230aa7">

However, I got this actually.
<img width="597" alt="スクリーンショット 2024-04-04 20 14 21" src="https://github.com/ecospat/ecospat/assets/99643952/ee0a4c5d-19f2-4092-94df-7a0fb9d81059">

I want to know why this have happened. 
I tried downgrading the package, but this didn't work. I tried installing `psych` and using `pairs.panel`, then it worked.(The right figure)
<img width="1400" alt="スクリーンショット 2024-04-04 10 18 00" src="https://github.com/ecospat/ecospat/assets/99643952/47188a33-ebc4-49b0-86b7-8e94bf83eab9">

Maybe my environment was the cause, but when I asked my colleague to download above data and run the following code, the result was the same.
My R version is following:
```
> R.version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          3.3                         
year           2024                        
month          02                          
day            29                          
svn rev        86002                       
language       R                           
version.string R version 4.3.3 (2024-02-29)
nickname       Angel Food Cake   
```
And the code is below:
```
library(ecospat)
data <- read.csv(“tabular/bioclim/current/bioclim_table.csv”, header=TRUE, sep=“,”)
ecospat.cor.plot(data[, 4:8])
```
I'm looking forward to understand the cause and use this package more.
Thank you in advance,

Kazuya

**Comment by FlavienCollart** [comment]
Hello,

you are totally right it is a bug. I corrected it, please try it by downloading our dev version: devtools::install_github("ecospat/ecospat/ecospat@dev")

Please let me know if it corrects the plot in your computer.

Have a great day,
Flavien

**Comment by Kazuya-Haganuma** [comment]
Dear Flavien,

Thank you for you kindly response.

I installed it and got the expected plot! :-)
(In addition to the histogram, the sign of the correlation was also corrected thankfully.)
<img width="582" alt="スクリーンショット 2024-04-16 10 30 14" src="https://github.com/ecospat/ecospat/assets/99643952/1300c4d0-0292-4220-a5b5-fa18deb9a0ad">

I am grateful for your help in getting the error fixed.

Best regards,
Kazuya

**Comment by FlavienCollart** [comment]
Hello,

Happy to read that the issue is solved! 

Cheers, 
Flavien
